confluence:
  url: https://tractorjunction1.atlassian.net/wiki
  space_key: Roshan
  hub_parent_title: Sprint Governance Hub

jira:
  url: https://tractorjunction1.atlassian.net
  boards:
    primary:
      id: 49
      name: CMP board
  projects:
    - DPC
    - FJPL
  ticket_filters:
    jql: >
      (summary ~ "TJ" OR summary ~ "TG" OR labels = TJ_WEB)
  fields:
    story_points: customfield_10035
    team_labels:
      - UI
      - DEV
      - QA
      - SEO
  done_statuses:
    - Closed
    - LIVE
    - LIVE VERIFICATION QA
    - LIVE VERIFICATION PM & SEO
  adhoc_label: AdHoc

sheets:
  spreadsheet_title: "Sprint Governance"
  spreadsheet_id: "1f2vYvfjmfz1PydO-FZfxrRAZDwwerg7-a-BAWh_yfPw"
  service_account_key: sprint-governance-0cdf032fd14f.json
